# Generated by Django 4.2.1 on 2023-05-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceedings', models.CharField(max_length=200)),
                ('auditable_unit', models.CharField(max_length=200)),
                ('url_auditable_unit', models.URLField()),
                ('name_social_reason', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('detail', models.URLField()),
            ],
        ),
    ]
