# Generated by Django 4.2.1 on 2023-05-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_alter_station_id_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='extra',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='network',
            name='href',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='network',
            name='id_network',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
