# Generated by Django 4.2.1 on 2023-05-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_alter_extra_address_alter_extra_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='altitude',
            field=models.IntegerField(null=True),
        ),
    ]
